services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  VPNMinute\InfrastructureProvisioner\Terraform:
    class: '\VPNMinute\InfrastructureProvisioner\Terraform'
    tags:
      - { name: 'can_be_fetched', class: 'InfrastructureProvisionerBag' }
