services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  VPNMinute\Core\:
    resource: '../../../src/Core/*'
    exclude: '../../../src/Core/DI/*'
    lazy: true

  VPNMinute\Core\Assembly\AssemblyDeliberationCacheProxy:
    decorates: 'VPNMinute\Core\Assembly\Assembly'

  # Infrastructure provisioner

  VPNMinute\Core\Voter\InfrastructureProvisioner\:
    resource: '../../../src/Core/Voter/InfrastructureProvisioner/*'
    tags:
      - { name: 'voter', class: 'InfrastructureProvisionerAssembly' }

  VPNMinute\Core\Bag\InfrastructureProvisionerBag:
    class: 'VPNMinute\Core\Bag\CanBeFetchedBag'

  VPNMinute\Core\Assembly\InfrastructureProvisionerAssembly:
    class: 'VPNMinute\Core\Assembly\Assembly'
    calls:
      - setSubject: ['infrastructureProvisioner']
      - setMethod: [3]

  VPNMinute\Core\Assembly\InfrastructureProvisionerAssemblyDeliberationCacheProxy:
    class: '\VPNMinute\Core\Assembly\AssemblyDeliberationCacheProxy'
    arguments:
      $canDeliberate: '@VPNMinute\Core\Assembly\InfrastructureProvisionerAssembly'

  VPNMinute\Core\Fetcher\InfrastructureProvisionerFetcher:
    class: '\VPNMinute\Core\Fetcher\Fetcher'
    arguments:
      $assemblyDeliberationCacheProxy: '@VPNMinute\Core\Assembly\InfrastructureProvisionerAssemblyDeliberationCacheProxy'
      $canBeFetchedClass: '@VPNMinute\Core\Bag\InfrastructureProvisionerBag'

  VPNMinute\Core\InfrastructureProvisioner:
    factory: ['@VPNMinute\Core\Fetcher\InfrastructureProvisionerFetcher', 'get']
    public: true
